exclude: [vendor]
include: ['_pages']
# Site settings
title: designaroni.com
email: hello@designaroni.com
description: > # this means to ignore newlines until "baseurl:"
  Senior Front End Designer @SportNgin - Eternally Minnesotan, Forever Curious… / Web Designer & Front-end Developer / Typographer / Coder / UI / UX /
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://designaroni.com" # the base hostname & protocol for your site
urlDevMode: "http://0.0.0.0:4000"
twitter_username: designaroni
github_username:  designaroni
hasComments: "#disqus_thread"
fadeImg: 'onload="fadeImg(this)" style="display: none;"'
fadeEl: 'onload="fadeEl(this)" style="display: none;"'
fadePauseFast: fade-in pause-fast
fadePauseSlow: fade-in pause-slow
fadeSlow:      fade-in slow
fadeFast:      fade-in fast
fontSans: tk-jaf-facitweb
fontSerif: tk-bookmania
headingEls: h1, h2, h3, h4, h5, h6, .site-header
clear: '<div class="clear"></div>'
devmode: false
# Build settings
markdown: kramdown
permalink: journal/:title
# Gems because wut?
gems:
  - jekyll-assets
# settings for Prose.io
prose:
  rooturl: '_posts'
  siteurl: 'http://designaroni.com'
  media: 'assets'
  ignore:
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "subtitle"
        field:
          element: "text"
          value: "title"
      - name: "date"
        field:
          element: "text"
          value: "CURRENT_DATETIME"
      - name: "categories"
        field:
          element: "multiselect"
          options:
            - name: 'Front End'
              value: 'front-end'
            - name: 'Terminal'
              value: 'terminal'
            - name: 'Jekyll'
              value: 'jekyll'
            - name: 'Code'
              value: 'code'
            - name: 'Career'
              value: 'career'
            - name: 'Architecture'
              value: 'architecture'
            - name: 'Professional Development'
              value: 'professional-development'
            - name: 'Character'
              value: 'character'
            - name: 'Tools'
              value: 'tools'
            - name: 'Sass'
              value: 'sass'
            - name: 'Javascript'
              value: 'javascript'
      - name: "leadImage"
        field:
          element: "text"
          label: "This is a label to the user"
          help: "this is a help to accompany the label"
          value:
          placeholder: "/assets/unsplash_vadim_sherbakov_26-9.jpeg"
      - name: "leadImageAlt"
        field:
          element: "text"
          placeholder: "subtitle"
      - name: "published"
        field:
          element: "checkbox"
          value: false
