---
title: designaroni.com
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
exclude:
- vendor
include:
- _pages
email: hello@designaroni.com
description: Senior Front End Developer, Team Lead for the Creative team @SportsEngine.
  Building custom web solutions for sport organizations, dealing with corporate branding,
  delivering marketing campaigns for the needy & obsessively improving Front End tooling,
  build processes & the like… all for the love of sport & code. - Eternally Minnesotan,
  Forever Curious… Web Designer & Front End Web Developer | Coder | UI | UX
baseurl: ''
url: http://designaroni.com
urlDevMode: http://0.0.0.0:4000
twitter_username: designaroni
github_username: designaroni
hasComments: "#disqus_thread"
fadeSlowPauseFastFade: fade-in slow-pause-fast-fade
fadeSlowPauseSlowFade: fade-in slow-pause-slow-fade
fadeFastPauseSlowFade: fade-in fast-pause-slow-fade
fadeMidSlowMidFade: fade-in mid-slow-mid-fade
fadeFastPauseFastFade: fade-in fast-pause-fast-fade
fade: fade-in
fontSans: tk-jaf-facitweb
fontSerif: tk-bookmania
headingEls: h1, h2, h3, h4, h5, h6, .site-header
clear: <div class="clear"></div>
center: <span class="center">
endDiv: "</span>"
listAllArticlesPostLinkWidth: 900px
devmode: false
forwardSlash: "/"
singleQuote: "'"
markdown: kramdown
permalink: journal/:title
gems:
- jekyll-assets
- jekyll-feed
- jekyll-sitemap
prose:
  rooturl: _posts
  siteurl: http://designaroni.com
  media: assets
  ignore: 
  metadata:
    _posts:
    - name: layout
      field:
        element: hidden
        value: post
    - name: title
      field:
        element: text
        label: title
    - name: subtitle
      field:
        element: text
        value: title
    - name: date
      field:
        element: text
        value: CURRENT_DATETIME
    - name: categories
      field:
        element: multiselect
        options:
        - name: Front End
          value: front-end
        - name: Terminal
          value: terminal
        - name: Jekyll
          value: jekyll
        - name: Code
          value: code
        - name: Career
          value: career
        - name: Architecture
          value: architecture
        - name: Professional Development
          value: professional-development
        - name: Character
          value: character
        - name: Tools
          value: tools
        - name: Sass
          value: sass
        - name: Javascript
          value: javascript
    - name: leadImage
      field:
        element: text
        label: This is a label to the user
        help: this is a help to accompany the label
        value: 
        placeholder: "/assets/unsplash_vadim_sherbakov_26-9.jpeg"
    - name: leadImageAlt
      field:
        element: text
        placeholder: subtitle
    - name: published
      field:
        element: checkbox
        value: false
