# Site settings
title: Designaroni.com
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Senior Front End Designer @SportNgin - Eternally Minnesotan, Forever Curious… / Web Designer & Front-end Developer / Typographer / Coder / UI / UX /
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: designaroni
github_username:  designaroni

# Build settings
markdown: kramdown
